# Generated by Django 5.0.6 on 2024-05-22 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='address',
            field=models.CharField(default=21, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cart',
            name='phone',
            field=models.CharField(default=12, max_length=15),
            preserve_default=False,
        ),
    ]
